print("\nWelcome to the tip calculator.\n")
total_bill = input("What was the total bill? $")
perc_tip = input("What percentage tip would you like to give? 10,20, or 15? ")
people_split_bill = input("How many people to split the bill? ")
each_pay = round(float(total_bill)/float(people_split_bill)*1.12,2)
print(f"Each person should pay: ${each_pay}")
